### PR TITLE
Fix smart charger values

### PR DESCRIPTION
**Pull request by crawfxrd**
Fix all smart charger values by having boards provide the RSENSE values and perform the register calculations in the code.

The galp3-c, galp5, gaze16, and gaze17 do not seem to have the same behavior as the rest of the boards, and further investigation is needed. In the mean time, reduce their charge current values to preserve current behavior.

Ref: OZ26786-DS v1.0
Ref: bq24780S Rev. C datasheet
Resolves: #286

### Test

- Drain battery to <90%
- Power off
- Plug in AC adatper to a Kill A Watt
- Check amps and watts while charging

After change, board should charge at ~30W.

### CODE REVIEW

**Review by 13r0ck — DISMISSED** [review]

**Comment by linuxgnuru** [comment]
Tested lemp11, darp8, oryp7, and gaze16-3050ti.
- lemp11 and darp8 averaged  ~31 watts
- oryp7 averaged ~ 24 watts
- gaze16-3050ti averaged above ~ 50 watts

**Comment by crawfxrd** [comment]
Do you have the values from before the change as well?

**Comment by linuxgnuru** [comment]
before:
darp8: 31.3
lemp11: 30.9
gaze16-3050ti: 28.9

**Comment by crawfxrd** [comment]
| Model         | Before        | After         |
| ------------- | ------------- | ------------- |
| darp8         | 32W, 0.30A    | 33W, 0.32A    |
| galp3-c*      | 22W, 0.36A    | 22W, 0.35A    |
| galp5         | 31W, 0.29A    | 60W, 0.55A    |
| gaze15        | 52W, 0.48A?   | 25W, 0.24A    |
| gaze16-3060   | 28W, 0.27A    | 52W, 0.50A    |
| gaze17-3060-b | 30W, 0.29A    | 58W, 0.53A    |
| lemp10        | 32W, 0.30A    | 32W, 0.30A    |
| lemp11        | 33W, 0.32A    | 33W, 0.32A    |
| oryp5*        | 25W, 0.24A    | 25W, 0.24A    |
| oryp6         |               |               |
| oryp8         | 24W, 0.24A    | 25W, 0.24A    |
| oryp9         | 39W, 0.38A    | 40W, 0.38A    |

*These units don't have an official release, `1add7eec31f5` was used instead.

So something is clearly up with gaze16, gaze17, galp3-c, and galp5. I've kept their charge current at 1.5A instead until the reason is determined.

**Comment by crawfxrd** [comment]
If the schematics are wrong. That's why I've left a comment for them:

```
# FIXME: Verify parts and values.
```

**Comment by XV-02** [comment]
Everything I can test (in the lab our galp5s are not available, nor is a galp-3c or lemp10, nor could I locate oryp5 or oryp6) is working *except Oryp9* which is reporting at ~47watts.

**Comment by crawfxrd** [comment]
Retested my oryp9, Kill A watt reports between 40-41 W and 0.37A while charging.

Can you check the battery and adapter to verify the values:

```
CHARGER_CHARGE_VOLTAGE=13050
CHARGER_INPUT_CURRENT=11500
```

**Comment by XV-02** [comment]
I was looking at the 15" Oryp9-3070. 
Where are you pulling
```
CHARGER_CHARGE_VOLTAGE=13050
CHARGER_INPUT_CURRENT=11500
```
from?

**Comment by crawfxrd** [comment]
See: https://github.com/system76/ec/blob/master/doc/adding-a-new-board.md#charger-parameters

**Comment by XV-02** [comment]
```
CHARGER_CHARGE_VOLTAGE=13050
CHARGER_INPUT_CURRENT=11500
```
This matches the values stated on the hardware.

**Comment by crawfxrd** [comment]
I've lowered oryp9 to 2A. It now charges at 29W / 0.28A on my unit.

**Review by XV-02 — DISMISSED** [review]
All tested models are now behaving as desired. Approving.

**Review by XV-02 — APPROVED** [review]
Smart-charging functionality has been successfully tested across all available models. Concern about incorrect testing has been addressed, and doesn't effect smart-charger functionality. Approving.

**Comment by crawfxrd** [comment]
I fixed `KBLIGHT_ADJ` and added galp6 to CI. Everything should be good now.

**Review by XV-02 — APPROVED** [review]
Fixed last outstanding issue. Good work. Approving.

**Review by 13r0ck — APPROVED** [review]

**Pull request merged**
