### PR TITLE
darp10: Add custom fan points

### PR DESCRIPTION
**Pull request by crawfxrd**

### CODE REVIEW

**Comment by XV-02** [comment]
If I'm reading this correctly, we're moving the fans between 27% and 77% duty cycles across the thermal range?

If that is correct, why are we capping at 77%?

**Comment by crawfxrd** [comment]
It's harder to make our fan tables now by only looking at the Clevo tables since:

- They use a ladder (10 levels) instead of a linear scale
- They use target RPM instead of PWM duty
- They no longer document noise generated

Since we don't support target RPM, I used the average between 2 of the 6 profiles that Clevo provides as the duty.

- Fan1 max: 7700 RPM
- Performance, level 9: 7700 RPM
- Quiet, level 9: 5400 RPM

I don't know the actual duty required for the 7700 RPM target, so I considered it 100%.

**Review by jackpot51 — APPROVED** [review]

**Comment by XV-02** [comment]
For the fan curves, where are we actually sampling the temps? are we using the "Package" temps or the "CPU" temp?

**Comment by crawfxrd** [comment]
We use PECI to read the package temperature every 250+ ms.

- `src/board/system76/common/peci.c`
- `src/board/system76/common/main.c`

From the PECI user guide:

- The GetTemp() command is used to retrieve the maximum die temperature from a target PECI address.
- The processor temperature is averaged over 256 ms.

**Comment by XV-02** [comment]
Okay, looks like the Max fan speeds are ~9000rpm +/- ~10% on the lab units. The duty cycle is working, and package/for temps are successfully driving fan speeds at the desired duty. 

Do you want to adjust the curves in light of different values for 100% duty than you expected? For reference, in a 25⁰C environment, building kernels and running stress loads aren't pulling temps much above 80⁰C, or fan speeds much above ~6200 rpm. If not, I'm comfortable to approve this.

**Comment by crawfxrd** [comment]
No, I'll leave it as-is. The primary concern with moving away from the default points on all boards is having the fans cool below 70⁰C.

I want to look into #453 more which will change how all this is defined anyways.

**Review by XV-02 — APPROVED** [review]

**Pull request merged**
