### PR TITLE
docs: Explicitly mention to use a USB cable

### PR DESCRIPTION
**Pull request by crawfxrd**
Replace the vague step about grounding with one that says to connect a USB cable and explain its purpose.

### CODE REVIEW

**Comment by jackpot51** [comment]
Thing is, that isn't the only way. I frequently use a USB-A cable.

**Comment by crawfxrd** [comment]
If USB-A works I can just say to use a USB cable. I remember you telling me to specifically use a USB-C cable at some point.

**Comment by jackpot51** [comment]
I think that is because USB-C handles host to host connections more better

**Comment by jackpot51** [comment]
How about:

Ground the laptop to the programmer. The recommended way to do this is with a USB-C cable connecting the laptop to the computer doing the proramming

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
