### PR TITLE
Adjust fan curve to prevent constant toggling of fan

### PR DESCRIPTION
**Pull request by CourchesneA**
Should fix 
https://github.com/system76/firmware-open/issues/250
and possibly
https://github.com/system76/ec/issues/241

With the fan curve, if the CPU/GPU temp is oscillating between two curve points, the fan will constantly produce annoying sound when they start and stop. This PR adds another curve point to make a smoother transition.

This is only a quick fix, it is assuming that "20" is a valid fan speed. In the long term, it would be useful to have a more robust solutions such as temperature averaging , smooth startup, conditional stopping of the fans or exposing the parameters to the user.

Linked is a GIF of the issue that I am trying to solve
fan_recording

### CODE REVIEW

**Comment by jackpot51** [comment]
20% is too low for the 17 inch oryx. It's fans have a minimum speed of 25%

**Comment by CourchesneA** [comment]
@jackpot51 Thanks for the info. I modified the PR to only change the temp where the fan starts from 55 to 50. The fan would still start at 25%, but it would solve the issue since I haven't seen my CPU go below 51 °C. The fan would always be on, but it seems a much better option than the constant toggling.

**Comment by jackpot51** [comment]
I have an oryp7 and will try this out, thanks

**Comment by jackpot51** [comment]
@curiousercreative we released #190 as of the 2021-07-20 release, which is available for most devices including the galp5.

**Comment by CourchesneA** [comment]
In the end this pull request did not resolve the issue. It seems whatever the value I put in the fan curve, the fan will always reduce the temp of the CPU until it reaches the minimum value to trigger the fan, and the temperature will oscillate around that value, triggering the fan to go on and off continuously. I have tried multiple options including the `CFLAGS+=-DBOARD_HEATUP`, but the only way that I have found that was able to make the noise less annoying is by adding the fan point `FAN_POINT(35, 25)` to make the fan always active. One possible alternative that I can see would be raising the fan point high enough, but that is assuming that light operations do not raise the CPU temp enough to be dangerous or damageable. I do not know enough about CPUs to test this, so I will close the PR

**Pull request closed without merging**
