### PR TITLE
Add Pause key

### PR DESCRIPTION
**Pull request by crawfxrd**
On proprietary firmware and in QMK, `Pause` and `Break` are the same thing. `Ctrl` must be held for the OS to register the key as `Break`.

Behavior tested with xev.

Resolves: #197

### CODE REVIEW

**Comment by ids1024** [comment]
I guess the Configurator also needs some way to know if the EC firmware is a newer version with support for these. (Just comparing the date from the version would more or less work, I suppose, without a better solution.)

**Review by jackpot51 — APPROVED** [review]

**Comment by jacobgkau** [comment]
On serw12 (proprietary firmware), `Pause` and `Break` both show up as keycode 127 (`Pause`). On oryp7 with this branch, `Pause` shows up as keycode 127, but `Break` shows up as keycode 37 (`Control L`).

**Comment by crawfxrd** [comment]
Yeah. Looking at the kudu6, they're both `Pause`, and you have to explicitly hold `LCtrl` to get `Break`. The 14in_86 keyboard (galp3-c/galp4) probably has the same behavior.

And I just checked QMK, it defines `KC_BRK` to `KB_PAUSE`.

So, no `Break`.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Pause and Break are both showing up with keycode 127 in `xev` as expected, PgUp/PgDn are still working normally when not holding Fn down.

Pause/Break are not showing up in the keyboard configurator, but that doesn't seem like an issue with the EC.

**Review by jackpot51 — APPROVED** [review]

**Pull request merged**
