### PR TITLE
Always power off if in S5 state on systems using eSPI

### PR DESCRIPTION
**Pull request by jackpot51**
This may fix issues with unresponsive power buttons.

### CODE REVIEW

**Comment by leviport** [comment]
After first flashing, the machine wouldn't react to anything I did to it until I reset CMOS. Afterwards, the lights on the front react as I would expect when plugging and unplugging the charger. However, now pressing the power button with the charger plugged in gives me this:
```
[15:45:21] 51: Power switch press
[15:45:21] 51: power_on
[15:45:21] VA_EC_EN = true
[15:45:21] DD_ON = true
[15:45:21] PCH_DPWROK_EC = true
[15:45:21] EC_RSMRST_N = true
[15:45:21] EC_EN = true
[15:45:21] PWR_BTN_N = false
[15:45:21] PWR_BTN_N = true
[15:45:21] POWER_STATE_S5
[15:45:26] failed to reach S0, powering off
[15:45:26] 51: power_off
[15:45:26] PCH_PWROK_EC = false
[15:45:26] PM_PWROK = false
[15:45:26] EC_EN = false
[15:45:26] EC_RSMRST_N = false
[15:45:26] DD_ON = false
[15:45:26] VA_EC_EN = false
[15:45:26] PCH_DPWROK_EC = false
[15:45:26] POWER_STATE_OFF
```
and nothing else. 

Something new happens if I disconnect the charger though. The console gets constantly flooded with lines like these:
```
[15:46:42] power_ppeci_limit unnknown responsee: 0x00
[15:46:42] power_pecci_limit 28 = 00
[15:46:42] power_peci_liimit unknown  response: 0x000
[15:46:42] oower_peci_limiit 28 = 0
[15:46:42] powerr_peci_limit unkknown responsee: 0x00
[15:46:42] power_peeci_limit 28 =  0
[15:46:42] power_peci_llimit unknown rresponse: 0x000
[15:46:42] power_peci_limiit 28 = 0
[15:46:42] poweer_peci_limit uunknown responsse: 0x00
[15:46:42] power_ppeci_limit 28 =  0
[15:46:42] power_peci_llimit unknown reesponse: 0x00
[15:46:42] powwer_peci_limitt 28 = 0
[15:46:42] power__peci_limit unknnown responsee: 0x00
[15:46:42] power_pecci_limit 28 = 00
[15:46:42] power_peci_liimit unknown reesponse: 0x000
[15:46:42] power_peci_limiit 28 = 0
[15:46:42] powerr_peci_limit uunknown responsee: 0x00
[15:46:42] power_ppeci_limit 28 =  0
[15:46:42] power_peci_llimit unknown  response: 0x000
[15:46:42] power_peci_liimit 28 = 0
[15:46:42] powerr_peci_limit uunknown responnse: 0x00
[15:46:42] power_ppeci_limit 28 =  0
[15:46:42] power_peci_liimit unknown  response: 0x000
[15:46:42] power_peci_limmit 28 = 0
[15:46:42] powerr_peci_limit unnknown responsse: 0x00
[15:46:42] power_ppeci_limit 28 == 0
[15:46:42] power_peci__limit unknown  response: 0x000
[15:46:42] power_peci_limiit 28 = 0
[15:46:42] poweer_peci_limit uunknown responsee: 0x00
[15:46:42] power_peeci_limit 28 = 00
[15:46:42] power_peci_llimit unknown rresponse: 0x000
[15:46:42] power_peci_liimit 28 = 0
[15:46:42] poweer_peci_limit  unknown responnse: 0x00
[15:46:42] power_ppeci_limit 28 == 0
[15:46:42] power_peci__limit unknownn response: 0x000
[15:46:42] power_peci_liimit 28 = 0
[15:46:42] powwer_peci_limit uunknown responnse: 0x00
[15:46:42] power_pecci_limit 28 = 0
```

Pressing the power button while it's doing that makes the flood stop briefly and I see the same sequence and timeout that I get while on the charger, but the flood resumes immediately after it times out:
```
[15:43:32] power_peci_liimit unknown reesponse: 0x00
[15:43:32] poower_peci_limitt 28 = 0
[15:43:32] power_ppeci_limit unkknown responsse: 0x00
[15:43:32] power_peeci_limit 28 =  0
[15:43:32] power_peci_liimit unknown rresponse: 0x00

[15:43:32] ower_peci_limit 28 == 0
[15:43:32] power_peci_llimit unknown  response: 0x000
[15:43:32] power_peci_limit 28 = 0  Current: 0000
[15:43:32]   Charge: 0064
[15:43:33]   Status: 00E0
[15:43:33] Charger (oz26786):
[15:43:33]   ChargeCurrent: 0600
[15:43:33]   ChargeVoltage: 41A0
[15:43:33]   ChargeOption_1: 0800
[15:43:33]   ChargeOption_2: 0800
[15:43:33]   AdapterCurrent: 1580
[15:43:38] 1B: Power switch press
[15:43:38] 1B: power_on
[15:43:38] VA_EC_EN = true
[15:43:38] DD_ON = true
[15:43:38] PCH_DPWROK_EC = true
[15:43:38] EC_RSMRST_N = true
[15:43:38] EC_EN = true
[15:43:38] PWR_BTN_N = false
[15:43:38] PWR_BTN_N = true
[15:43:38] POWER_STATE_S5
[15:43:43] failed to reach S0, powering off
[15:43:43] 1B: power_off
[15:43:43] PCH_PWROK_EC = false
[15:43:43] PM_PWROK = false
[15:43:43] EC_EN = false
[15:43:43] EC_RSMRST_N = false
[15:43:43] DD_ON = false
[15:43:43] VA_EC_EN = false
[15:43:43] PCH_DPWROK_EC = false
[15:43:43] POWER_STATE_OFF
[15:45:21] 51: Power switch press
[15:45:21] 51: power_on
[15:45:21] VA_EC_EN = true
[15:45:21] DD_ON = true
[15:45:21] PCH_DPWROK_EC = true
[15:45:21] EC_RSMRST_N = true
[15:45:21] EC_EN = true
[15:45:21] PWR_BTN_N = false
[15:45:21] PWR_BTN_N = true
[15:45:21] POWER_STATE_S5
[15:45:26] failed to reach S0, powering off
[15:45:26] 51: power_off
[15:45:26] PCH_PWROK_EC = false
[15:45:26] PM_PWROK = false
[15:45:26] EC_EN = false
[15:45:26] EC_RSMRST_N = false
[15:45:26] DD_ON = false
[15:45:26] VA_EC_EN = false
[15:45:26] PCH_DPWROK_EC = false
[15:45:26] POWER_STATE_OFF
[15:46:39] power_peci_limit: 80FA
[15:46:39]   Current: 0000
[15:46:39]   Chargemit unknown rresponse: 0x00

[15:46:39] oower_peci_limiit 28 = 0
[15:46:39] poweer_peci_limit unnknown responsse: 0x00
[15:46:39] power_peeci_limit 28 == 0
[15:46:39] power_peci__limit unknown  response: 0xx00
[15:46:39] power_peci_liimit 28 = 0
[15:46:39] powwer_peci_limit  unknown responnse: 0x00
[15:46:39] power__peci_limit 28 == 0
```

**Comment by leviport** [comment]
Actually, scratch that. Turns out I flash gaze16-3060 EC firmware to this gaze16-3050. Whoops. After flashing the correct version, it seems pretty happy now. I'm going to see if I can get it stuck again.

**Comment by leviport** [comment]
I was able to get it into one of its stuck states again. This time it was the one where it times out trying to reach S0:
```
[13:43:42] 66: Power switch press
[13:43:42] 66: power_on
[13:43:42] VA_EC_EN = true
[13:43:42] DD_ON = true
[13:43:42] PCH_DPWROK_EC = true
[13:43:42] EC_RSMRST_N = true
[13:43:42] EC_EN = true
[13:43:42] PWR_BTN_N = false
[13:43:42] PWR_BTN_N = true
[13:43:42] POWER_STATE_S5
[13:43:47] failed to reach S0, powering off
[13:43:47] 66: power_off
[13:43:47] PCH_PWROK_EC = false
[13:43:47] EC_EN = false
[13:43:47] EC_RSMRST_N = false
[13:43:47] DD_ON = false
[13:43:47] VA_EC_EN = false
[13:43:47] PCH_DPWROK_EC = false
[13:43:47] POWER_STATE_OFF
[13:54:19] 78: Power switch press
[13:54:19] 78: power_on
[13:54:19] VA_EC_EN = true
[13:54:19] DD_ON = true
[13:54:19] PCH_DPWROK_EC = true
[13:54:19] EC_RSMRST_N = true
[13:54:19] EC_EN = true
[13:54:19] PWR_BTN_N = false
[13:54:19] PWR_BTN_N = true
[13:54:19] POWER_STATE_S5
[13:54:24] failed to reach S0, powering off
[13:54:24] 78: power_off
[13:54:24] PCH_PWROK_EC = false
[13:54:24] EC_EN = false
[13:54:24] EC_RSMRST_N = false
[13:54:24] DD_ON = false
[13:54:24] VA_EC_EN = false
[13:54:24] PCH_DPWROK_EC = false
[13:54:24] POWER_STATE_OFF
```

Pulling the battery and charger, then plugging in the charger allowed it to boot normally after this.

**Review by crawfxrd — APPROVED** [review]

**Review by XV-02 — APPROVED** [review]
Resolves the Darp8 mixed power-state issue, not causing issues elsewhere. Approved.

**Pull request merged**
