### PR TITLE
tool: Update dependencies

### PR DESCRIPTION
**Pull request by crawfxrd**
clap is only updated to 3.2 instead of 4.0 because I didn't want to deal with all the changes.

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Review by jacobgkau — CHANGES_REQUESTED** [review]
Tested on oryp9. Building still works, but after this change, flashing with `./scripts/flash oryp9` from the firmware-open directory fails at the EC step with this error:

```
SPI VERIFY: 32 MB
  Downloaded hidapi v1.4.2
  Downloaded os_str_bytes v6.3.0
error: failed to parse manifest at `/home/system76/.cargo/registry/src/github.com-1ecc6299db9ec823/os_str_bytes-6.3.0/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

**Comment by crawfxrd** [comment]
The toolchain file in firmware-open is updated by https://github.com/system76/firmware-open/pull/304.

Alternatively, `flash.sh` should be changed to use `pushd`/`popd` so the EC project toolchain is used.

**Comment by jacobgkau** [comment]
> The toolchain file in firmware-open is updated by [system76/firmware-open#304](https://github.com/system76/firmware-open/pull/304).

I see. That PR's marked as draft; I can take a look at this again either when it's marked ready for review or when we have a PR to make the `flash.sh` change you mentioned as an alternative.

**Review by jackpot51 — APPROVED** [review]

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — DISMISSED** [review]

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Builds & flashes now (tested on darp7).

**Pull request merged**
