### PR TITLE
Add scroll lock to default keymaps

### PR DESCRIPTION
**Pull request by crawfxrd**
I don't know anything that uses this, so I only checked that xev reported the key as scroll lock.

Resolves: #223

### CODE REVIEW

**Review by jackpot51 — DISMISSED** [review]

**Comment by leviport** [comment]
- [ ] darp6 ISO layout (15" 102 key, ISO)
- [ ] darp6 ANSI layout (15" 102 key)
- [ ] bonw14 (15" 102 key with n-key rollover) -- **No lab unit here to test with**
- [ ] galp4 (14" 86 key)
- [ ] lemp10 (14" 83 key)

**Review by leviport — CHANGES_REQUESTED** [review]
I'm not sure we should add Scroll Lock to 14in_83 since Scroll Lock was never printed on lemp9/lemp10's keyboard. The preprod lemp9 we have has it printed, but the ones we actually shipped do not.

**Comment by crawfxrd** [comment]
Dropped from `14in_83`. galp5 also uses it, but I don't think they print the function on the key either.

**Comment by leviport** [comment]
Yep, galp5's keycaps are printed the same as lemp9/10. 

We'll get the bonw14 tested later today. If that looks good, then we'll approve.

**Review by jackpot51 — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
bonw14's working fine as well. On Pop!_OS, I did need to run `xmodmap -e 'add mod3 = Scroll_Lock'` before the scroll lock would actually toggle on and off (before that, I saw the key being pressed, but the toggle wouldn't turn on.) The Insert key and the rest of the keyboard still work as expected.

**Pull request merged**
